name: E2E Tests con Python y Playwright

on:
  push:
    branches: [ main ]

  workflow_dispatch:

# Trabajos a ejecutar
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: make install

      - name: Crear archivo .env
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" > .env

      - name: Ejecutar los tests
        continue-on-error: true
        run: make test

      # Guarda los resultados de Allure como un "artefacto"
      - name: Subir reporte de Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results/
