name: Ejecutar Pruebas y Publicar Reporte

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permisos: Le damos permisos explícitos para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # --- EJECUTAR LOS TESTS ---
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Instalar dependencias
        run: make install
      - name: Crear archivo .env
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
      - name: Ejecutar los tests
        continue-on-error: true
        run: make test
      - name: Guardar resultados de Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  # --- DESPLEGAR EL REPORTE ---
  deploy-report:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest

    # Definimos la URL de salida
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Instalar Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          sudo tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure
      - name: Descargar resultados de los tests
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - name: Generar reporte HTML
        run: allure generate allure-results --clean -o allure-report

      - name: Preparar GitHub Pages
        uses: actions/configure-pages@v4
      - name: Subir artefacto de la página
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
